### PR TITLE
Move pretty printing output towards Kitware's house style

### PR DESCRIPTION
**Pull request by robertknight**
I'd like to use this library for auto-reformatting of all the CMakeLists.txt in our project.

This PR makes some changes to the cmake_pp output to follow Kitware's own style for CMakeLists.txt, on the basis that this is probably the best 'default' option for an auto-reformatting tool.
- Add an option to prettify() to make formatting configurable for projects that need it
- Lower-case command names in the output for consistency
- Change default indent to two spaces
- Make the tests runnable with 'python -m unittest discover'
- Refactor formatting of command arguments to make it easier to implement different formatting approaches as needed
- Fix an issue where 'elseif()' was not indented correctly

### CODE REVIEW

**Comment by wjwwood** [comment]
Cool, thanks for the pull, let me have a look at it and I'll get back to you asap.

**Comment by wjwwood** [comment]
Thanks again for pull, I've merged it and it's released as 0.4.1. I also took the opportunity to clarify the license as Apache 2.0 and properly attribute the copyright.

**Comment by robertknight** [comment]
@wjwwood - Could you enable issue tracking in GitHub for this repo? I found some additional bugs in testing which I'd like to record until I'm able to submit PRs to fix them.

**Comment by wjwwood** [comment]
Didn't realize they were off, but they're back on now.

**Pull request merged**
